### PR TITLE
feat: Add workflow to ensure conventional style on pull requests

### PR DESCRIPTION
**Pull request by Namchee**
## Overview

This pull request adds a workflow to ensure that all submitted pull request follows the [conventional commit convention](https://www.conventionalcommits.org/en/v1.0.0/).

The workflow itself uses my personal GitHub Action, [conventional-pr](https://github.com/marketplace/actions/conventional-prs).

> Note: The workflow will fail right now, since we haven't set the `ACCESS_TOKEN` yet.

### CODE REVIEW

**Comment by chez14** [comment]
Can `ACCESS_TOKEN` be sourced from `GH_TOKEN`?

**Comment by Namchee** [comment]
@chez14 , technically it's anything that you find under the `Personal Access Token` tab on the Settings page, so I think you can use `GH_TOKEN` but I need to confirm it.

**Comment by chez14** [comment]
Gotcha. You may use the token to do that. The token should provide enough level to close, reject and comment the PR as it usually be.

Anyway, as this is quite trivia, i can change this one by my self when i'm free. Or if you don't want to wait, you have my permission to use the token for this ;)

Thank you for the hard work, this hopefully will serve enough data for you to test and improve your projects as i will definitely always be rejected by this PR lol.

---

Quick question, is there any chance that this will reject PR from Dependabot??

**Comment by Namchee** [comment]
@chez14, unfortunately it will.

Great catch though, it's a new options then!

**Comment by Namchee** [comment]
@chez14, I've bumped the version. Should be okay to use [dependabot](https://github.com/dependabot) now.

**Comment by repurika** [comment]
:rocket: PR was released in [`v0.2.0`](https://github.com/direbus/daily-watori/releases/tag/v0.2.0) :rocket:

**Pull request merged**
